name: h_utils
description: Extend you code beyond reach with HUtils.
version: 0.0.4
homepage: https://booza.app

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.0
  date_format: ^1.0.6 # fix version


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

