name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: 'v1.12.13+hotfix.5'
    - run: flutter pub get
    - run: flutter test
#    - name: Flutter CLI
#      uses: steebchen/flutter@v1.0.0
#      run:
