# Copyright (c) 2020 Robert Hjortsholm Moeller

name: Test Action
on:
  push:
    branches:
      - test/*
jobs:
  cider:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r artifact.zip ./

      - name: Versioning
        id: versioning
        run: |
          pub global activate cider
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          echo "##[set-output name=version;]v$(cider version)"
          cider describe $(cider version) | grep "^\#\#\#\|^\-" > RELEASE.md

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          body_path: ./RELEASE.md
          draft: false
          prerelease: false
