# Copyright (c) 2020 Robert Hjortsholm Moeller

name: Test Action
on:
  push:
    branches:
      - test/*
jobs:
  cider:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: ./.github/workflows/actions/git-release
