# Copyright (c) 2020 Robert Hjortsholm Moeller

name: Test Action
on:
  push:
    branches:
      - test/*
jobs:
  cider:
    name: Release
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Versioning
        run: |
          pub global activate cider
          echo ${{ github.ref }}
          echo Updating Path
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          ls -al
          cider log add 'Test'
          cat CHANGELOG.md
          echo v$(cider version)

