# Copyright (c) 2020 Robert Hjortsholm Moeller

name: Test Action
on:
  push:
    branches:
      - test/*
jobs:
  cider:
    name: Release
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Versioning
      - id: foo
        run: |
          pub global activate cider
          echo ${{ github.ref }}
          echo Updating Path
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          echo "##[set-output name=version;]v$(cider version)"
