# Copyright (c) 2020 Robert Hjortsholm Moeller

name: Test Action
on:
  push:
    branches:
      - test/*
jobs:
#  test:
#    name: Dependencies
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: 'stable'
#      - run: flutter pub get
  cider:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Versioning
        run: |
          pub global activate cider
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cider describe 0.0.5
          echo ${{ github.ref }}
